# Generated by Django 3.1.2 on 2020-11-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201109_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('TOYS', 'Toys'), ('ELECTRONICS', 'Electronics'), ('FURNITURE', 'Furniture'), ('CARS', 'Cars'), ('HOME', 'Home'), ('OTHERS', 'Others')], default='OT', max_length=13),
        ),
    ]
