# Generated by Django 3.1.2 on 2020-11-15 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_listing_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlisted_users',
            field=models.ManyToManyField(default=None, related_name='watchlisted_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('TOYS', 'Toys'), ('ELECTRONICS', 'Electronics'), ('FURNITURE', 'Furniture'), ('CARS', 'Cars'), ('HOME', 'Home'), ('OTHERS', 'Others')], default='OTHERS', max_length=13),
        ),
    ]
